name: Pella自动续期

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  checkin:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r pella-checkin/requirements.txt
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Run auto checkin
      env:
        LEAFLOW_ACCOUNTS: ${{ secrets.PELLA_ACCOUNTS }}
        LEAFLOW_EMAIL: ${{ secrets.PELLA_EMAIL }}
        LEAFLOW_PASSWORD: ${{ secrets.PELLA_PASSWORD }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        GITHUB_ACTIONS: true
      run: |
        python pella-checkin/pella_checkin.py
